[versions]
kotlin = "2.1.0"
kotlin-dsl = "5.1.1"
kord = "0.15.0"
pubgkt = "0.0.1"
logback = "1.5.12"

[plugins]
kotlin-jvm = { id = "org.jetbrains.kotlin.jvm", version.ref = "kotlin" }
kotlin-dsl = { id = "org.gradle.kotlin.kotlin-dsl", version.ref = "kotlin-dsl" }

[libraries]
kotlin-test = { module = "org.jetbrains.kotlin:kotlin-test", version.ref = "kotlin" }

kord = { module = "dev.kord:kord-core", version.ref = "kord" }

pubgkt = { module = "pubgkt:pubgkt-jvm", version.ref = "pubgkt" }

logback-classic = { module = "ch.qos.logback:logback-classic", version.ref = "logback" }
