apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: pubg-stats-bot-prd
  name: pubg-stats-bot-deployment
  labels:
    app: pubg-stats-bot
spec:
  replicas: 1
  selector:
    matchLabels:
      app: pubg-stats-bot
  template:
    metadata:
      labels:
        app: pubg-stats-bot
    spec:
      containers:
        - name: pubg-stats-bot-app
          image: tavolatech.azurecr.io/pubg-stats-bot:latest
          envFrom:
            - configMapRef:
                name: pubg-stats-bot-config
      imagePullSecrets:
        - name: acr-secrets
